### ISSUE TITLE
Problem with footer position

### ISSUE THREAD

**Issue by ajsya** [ajsya/ajsya.github.io#2]
The footer won't go to the bottom of the page! I want it to go to the very bottom of the page but not always be visible.

**Comment by smileycreations15** [comment]
I cannot see the issue :(

**Comment by ajsya** [comment]
![Screenshot 2019-08-01 at 11 29 35](https://user-images.githubusercontent.com/52182942/62306352-b72b6000-b44f-11e9-91c1-59977e89bfdb.png)

**Comment by ajsya** [comment]
See the gap in the image?

**Comment by smileycreations15** [comment]
Ok, will do!
