### ISSUE TITLE
There is a big gap

### ISSUE THREAD

**Issue by ajsya** [ajsya/ajsya.github.io#3]
So I changed somethings and now the website embeds the header from the resource file but there's a big gap under the header, why is this happening?

**Comment by smileycreations15** [comment]
wait...

**Comment by ajsya** [comment]
I think I need to define the hight when I embed it

**Comment by ajsya** [comment]
It still won't work...

**Comment by smileycreations15** [comment]
yep

**Comment by ajsya** [comment]
I think I fixed it somehow

**Comment by smileycreations15** [comment]
ok
